### ISSUE TITLE
Automatic Node Size when parameter is set to 0

### ISSUE THREAD

**Issue by altarofwisdom-perso** [neilbaldwin/mmmsegui#1]
Currently, if I set nodesize to 0, the nodes disappear and cannot be modified.
It would be nice to use this value for automatic node dimension to avoid setting that up, or for resizeable windows.
Using max(2.5, max(width,height)) where width and height are the dimensions of the JSUI made good results for me on regular function.
Cheers !

**Comment by neilbaldwin** [comment]
Ah, thanks for feeding that back, much appreciated. I’ll have a pass over all the parameters and ensure sensible limits 👍

Neil

**Comment by neilbaldwin** [comment]
I was going to just steal your calculation but I don’t quite understand how that would work: it looks like it would set the size to be the largest of 2.5 or (JSUI width) or (JSUI height). So if the window is 400 x 300 it would set the node size to 400?

Neil

**Comment by altarofwisdom-perso** [comment]
Oops my bad, here's the actual computation I did:
v1 = (width+height)/750
v2 = max(1, v1)
nodesize = max(2.5,v2*2)
where nodesize is the radius

I also update the line thickness accordingly to v2

**Comment by neilbaldwin** [comment]
Haha, slightly different! I thought I was going mental :D

Neil

**Comment by altarofwisdom-perso** [comment]
Converting max patcher into formulas is not as easy as it seems :p
BTW noticing that these values cannot be updated without resetting the js, right ?
Corrected (again), the formula, time to get some rest I'd say

**Comment by neilbaldwin** [comment]
So would you suggest removing the node size option altogether?

**Comment by altarofwisdom-perso** [comment]
I would keep it, but default to "0" aka auto ?

**Comment by altarofwisdom-perso** [comment]
And do the same for line width

**Comment by neilbaldwin** [comment]
Sure 👍

**Comment by neilbaldwin** [comment]
That is true currently, yes.

I should probably just look at making it fully scaleable (on resize) but that’s a large amount of work. One day :)

In the meantime I could look at making certain parameters settable without recompiling. Any in particular?

**Comment by altarofwisdom-perso** [comment]
Mainly colors, nodes and lines, I'd say.
Domains as well could be updateable (with nodes following or not the domains) ?

**Comment by neilbaldwin** [comment]
Colors already works - see my example .maxpat

Node size and lines should be no problem. What do you mean by “domains”?

**Comment by altarofwisdom-perso** [comment]
horizontal and vertical range.
Also, displaying values while hovering would be nice, and maybe values for each point, plus grids...

**Comment by neilbaldwin** [comment]
This is done and will be in the next version.

**Comment by neilbaldwin** [comment]
Username: ***@***.***
My Cloud Drive folder: /Users/neilbaldwin/Cloud-Drive
Start Time: 12-16-2023 09:58:55

12-16-2023 09:58:55 :  [Full Sync up] File: /TBD Training/images/Heat Exchanger - Cold Water Inlet.jpg File size: 2.72 MB
12-16-2023 09:58:55 :  [Full Sync up] File: /TBD Training/images/Mash Tun Outlet (to HWT pump).jpg File size: 2.19 MB
12-16-2023 09:58:55 :  [Full Sync up] File: /TBD Training/images/Heat Exchanger - Outlet from Mash Tun.jpg File size: 2.22 MB
