### ISSUE TITLE
[Request] Delete all points except first and last ones with a message

### ISSUE THREAD

**Issue by samuelborrasca** [neilbaldwin/mmmsegui#2]
Delete all points at once (except for the first and last which can't be deleted) by sending a message to the inlet, e.g. [clear].
This would be useful for when mmmsegui gets busy with a lot of points, and the user would like to initialize/start over without deleting points one by one.

**Comment by neilbaldwin** [comment]
Working on this right now. You'll like it :)

**Comment by neilbaldwin** [comment]
Done and will be included in the new version.
