### ISSUE TITLE
[Request] Reset curve value to 0

### ISSUE THREAD

**Issue by samuelborrasca** [neilbaldwin/mmmsegui#3]
Reset the value of a curved segment between two points to 0, e.g. by double clicking or Ctrl (Win) / Cmnd (Mac) + clicking on it.

**Comment by neilbaldwin** [comment]
Got this working, SHIFT + double-clicking a curve segment will reset it to a linear curve.

It will be in the next release....very soon.

**Comment by neilbaldwin** [comment]
This is done and will be in the next version.

**Comment by neilbaldwin** [comment]
Closed.
